# Generated by Django 5.2.8 on 2025-12-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_habitlog_unique_together_habitlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='workout_type',
            field=models.CharField(choices=[('warmup', 'Aquecimento'), ('strength', 'Força'), ('cardio', 'Cardio/HIIT')], default='strength', help_text='Tipo do treino: Aquecimento, Força ou Cardio/HIIT', max_length=20),
        ),
    ]
